### ISSUE TITLE
Itemtypes display

### ISSUE THREAD

**Issue by Naylin15** [ajsb85/angular-glpi#4]
Hi @Gianfranco97 

Could you please add in the project site an improved list display for the Itemtypes? So it can be properly displayed, since it is very extensive for the readme

Thank you

**Comment by Gianfranco97** [comment]
sure, I'll work into it 👍

**Comment by Gianfranco97** [comment]
![screenshot-2017-10-13 angularjs glpi](https://user-images.githubusercontent.com/19965590/31556242-1deef05c-b012-11e7-968e-fdef13a30e43.png)
